
add_library(WebGPU STATIC IMPORTED GLOBAL)

set_target_properties(WebGPU PROPERTIES
	INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/include"
	IMPORTED_LOCATION "${CMAKE_CURRENT_LIST_DIR}/dawn.lib"
)
